#!/usr/bin/env python3
# Embed every Nari stdlib module (prelude + std/*) into a single generated
# C++ source file that exposes:
#
#     std::string nari_std_prelude_source();                      // implicit prelude
#     const std::string& nari_std_module_source(const std::string& name); // "" if unknown
#     const std::vector<std::string>& nari_std_module_names();    // sorted module names
#
# Invocation:
#     embed_std_modules.py <output.cpp> <prelude.nari> [name1=path1 name2=path2 ...]
#
# Names follow the import spec the parser will understand, e.g. "date" is
# imported as `import { Date } from "std/date";`.

from __future__ import annotations
import io
import os
import sys


def choose_delim(content: str, base: str = "EMBED") -> str:
    for i in range(0, 10000):
        delim = base if i == 0 else f"{base}_{i}"
        if delim not in content:
            return delim
    raise RuntimeError("Unable to find suitable raw-string delimiter")


def chunk_text(content: str, chunk_size: int = 12000) -> list[str]:
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    return [content[i:i + chunk_size] for i in range(0, len(content), chunk_size)] or [""]


def emit_string_literal(content: str) -> str:
    """Return a C++ expression that constructs the literal `content` as a
    sequence of adjacent raw-string chunks (MSVC-friendly)."""
    delim = choose_delim(content, base="EMBED_STD")
    parts = [f'R"{delim}({chunk}){delim}"' for chunk in chunk_text(content)]
    return "\n        ".join(parts)


def read_text(path: str) -> str:
    try:
        with io.open(path, "r", encoding="utf-8") as f:
            return f.read()
    except UnicodeDecodeError:
        with io.open(path, "r", encoding="latin-1") as f:
            return f.read()


def main(argv=None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if len(argv) < 2:
        print("usage: embed_std_modules.py <output.cpp> <prelude.nari> [name=path ...]",
              file=sys.stderr)
        return 2

    output = argv[0]
    prelude_path = argv[1]
    module_specs = argv[2:]

    if not os.path.exists(prelude_path):
        print(f"error: prelude not found: {prelude_path}", file=sys.stderr)
        return 2

    modules: list[tuple[str, str]] = []  # (name, content)
    for spec in module_specs:
        if "=" not in spec:
            print(f"error: bad module spec '{spec}', expected name=path", file=sys.stderr)
            return 2
        name, path = spec.split("=", 1)
        name = name.strip()
        path = path.strip()
        if not name or not path:
            print(f"error: empty name or path in '{spec}'", file=sys.stderr)
            return 2
        if not os.path.exists(path):
            print(f"error: module not found: {path}", file=sys.stderr)
            return 2
        modules.append((name, read_text(path)))

    modules.sort(key=lambda kv: kv[0])  # stable order for determinism

    prelude_src = read_text(prelude_path)

    out_lines: list[str] = []
    out_lines.append("// This file is generated by tools/embed_std_modules.py - DO NOT EDIT BY HAND.")
    out_lines.append("// Embeds the Nari stdlib prelude and every std/* module as raw strings.\n")
    out_lines.append("#include <string>")
    out_lines.append("#include <unordered_map>")
    out_lines.append("#include <vector>\n")

    # prelude
    out_lines.append("std::string nari_std_prelude_source() {")
    out_lines.append("    return std::string(")
    out_lines.append("        " + emit_string_literal(prelude_src))
    out_lines.append("    );")
    out_lines.append("}\n")

    # registry: per-module function returning the module source, plus an
    # accessor that maps a name to one of those functions.
    out_lines.append("namespace {")
    for idx, (name, content) in enumerate(modules):
        out_lines.append(f"const std::string& nari_std_module_source_{idx}() {{")
        out_lines.append(f"    static const std::string kSrc = std::string(")
        out_lines.append("        " + emit_string_literal(content))
        out_lines.append("    );")
        out_lines.append("    return kSrc;")
        out_lines.append("}")
    out_lines.append("} // anonymous namespace\n")

    out_lines.append("const std::string& nari_std_module_source(const std::string& name) {")
    out_lines.append("    static const std::string kEmpty;")
    if not modules:
        out_lines.append("    (void)name;")
        out_lines.append("    return kEmpty;")
    else:
        for idx, (name, _content) in enumerate(modules):
            out_lines.append(f'    if (name == "{name}") return nari_std_module_source_{idx}();')
        out_lines.append("    return kEmpty;")
    out_lines.append("}\n")

    out_lines.append("const std::vector<std::string>& nari_std_module_names() {")
    if modules:
        names_inits = ", ".join(f'"{name}"' for name, _content in modules)
        out_lines.append(f"    static const std::vector<std::string> kNames = {{ {names_inits} }};")
    else:
        out_lines.append("    static const std::vector<std::string> kNames;")
    out_lines.append("    return kNames;")
    out_lines.append("}")
    out_lines.append("")

    cpp = "\n".join(out_lines)

    outdir = os.path.dirname(output)
    if outdir and not os.path.exists(outdir):
        os.makedirs(outdir, exist_ok=True)

    with io.open(output, "w", encoding="utf-8", newline="\n") as f:
        f.write(cpp)

    return 0


if __name__ == "__main__":
    sys.exit(main())
