#!/usr/bin/env python3
# Embed a resource text file into a generated C++ source file as a function that
# returns the file contents as an std::string.
#
# ie. python3 tools/embed_resource.py <input_file> <output_cpp> <function_name>

from __future__ import annotations
import argparse
import sys
import io
import os

def choose_delim(content: str, base: str = "EMBED") -> str:
    """
    Choose a delimiter token not present in content. The delimiter will be used
    in a raw string literal like R"DELIM(...)DELIM". We try base, base_1, base_2, ...
    """

    for i in range(0, 10000):
        delim = base if i == 0 else f"{base}_{i}"
        if delim not in content:
            return delim
    raise RuntimeError("Unable to find suitable raw-string delimiter not present in the input")

def generate_cpp(function_name: str, content: str) -> str:
    """
    Produce C++ source text that defines `std::string <function_name>()` returning
    `content` via a raw string literal.
    """
    delim = choose_delim(content, base="EMBED_STD")
    # Ensure the function name is used as-is. Caller may pass names with namespaces (e.g. ns::fn).
    # we will generate a plain function definition: std::string <name>() { ... }
    # If the name contains characters invalid for a C++ identifier (like '::'), that's still valid as
    # a qualified name in a definition, so it's allowed.
    header = (
        "// This file is generated by tools/embed_resource.py - DO NOT EDIT BY HAND.\n"
        "// Embedded resource function: {}\n\n"
        "#include <string>\n\n"
    ).format(function_name)

    # Use a raw string literal. Keep the exact contents (including trailing newlines).
    raw = 'R"{delim}({content}){delim}"'.format(delim=delim, content=content)

    cpp = (
        header +
        "std::string {fn}() {{\n"
        "    // Return the embedded resource as an std::string.\n"
        "    // Using a raw string literal prevents the need for escaping.\n"
        "    return std::string({raw});\n"
        "}}\n"
    ).format(fn=function_name, raw=raw)

    return cpp

def main(argv=None):
    p = argparse.ArgumentParser(description="Embed a text resource into a generated C++ source.")
    p.add_argument("input", help="Path to input resource file (text)")
    p.add_argument("output", help="Path to output C++ source file to generate")
    p.add_argument("function", help="Name of the generated function returning the resource (e.g. nari_embedded_stdlib)")
    args = p.parse_args(argv)

    if not os.path.exists(args.input):
        print(f"Error: input file does not exist: {args.input}", file=sys.stderr)
        return 2

    try:
        with io.open(args.input, "r", encoding="utf-8") as f:
            content = f.read()
    except UnicodeDecodeError:
        with io.open(args.input, "r", encoding="latin-1") as f:
            content = f.read()

    try:
        cpp = generate_cpp(args.function, content)
    except Exception as e:
        print(f"Error generating C++ source: {e}", file=sys.stderr)
        return 3

    outdir = os.path.dirname(args.output)
    if outdir and not os.path.exists(outdir):
        try:
            os.makedirs(outdir, exist_ok=True)
        except Exception as e:
            print(f"Error creating output directory {outdir}: {e}", file=sys.stderr)
            return 4

    try:
        with io.open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(cpp)
    except Exception as e:
        print(f"Error writing output file {args.output}: {e}", file=sys.stderr)
        return 5

    return 0

if __name__ == "__main__":
    sys.exit(main())
